config/routes.rb
Media::Application.routes.draw do

  root :to => 'talks#index'

  get "video/:id" => 'video#show'

  resources :media

  resources :confrences

  resources :presenters

  resources :talks

end

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :description, :name, :presenters

  validates :name,  :presence => true,
                    :length => { :minimum => 5 }

  has_and_belongs_to_many :presenters
  
  # returns an array containing presenter's names and links to their profiles
  def peoplelinks
  	links = Array.new
  	presenters.each do |p|
  		if p[:handle] && p[:name] then
  			name = "#{p[:name].split(" ")[0]} \"#{p[:handle]}\" #{p[:name].split(" ")[1]}"
  		else
  			
        if p[:handle] then name = p[:handle] end
        if p[:name] then name = p[:name] end
  		
      end

  		links.push(:name => name, :link => "presenters/#{p[:id]}")
  	end
  	return links
  end

end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  # GET /talks
  # GET /talks.json
  def index
    @talks = Talk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @talks }
    end
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
    @talk = Talk.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @talk }
    end
  end

  # GET /talks/new
  # GET /talks/new.json
  def new
    @talk = Talk.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @talk }
    end
  end

  # GET /talks/1/edit
  def edit
    @talk = Talk.find(params[:id])
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(params[:talk])

    respond_to do |format|
      if @talk.save
        format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
        format.json { render json: @talk, status: :created, location: @talk }
      else
        format.html { render action: "new" }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /talks/1
  # PUT /talks/1.json
  def update
    @talk = Talk.find(params[:id])

    respond_to do |format|
      if @talk.update_attributes(params[:talk])
        format.html { redirect_to @talk, notice: 'Talk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy

    respond_to do |format|
      format.html { redirect_to talks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :presenters %><br />
    <%= f.text_field :presenters %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<h1>Listing talks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Presenters</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @talks.each do |talk| %>
  <tr>
    <td><a href="/video/<%= talk[:id] %>" class="video-links"><%= talk.name %></a></td>
    <td>
      <% talk.peoplelinks.each do |p| %>
      <a href="<%= p[:link] %>"><%= p[:name] %></a>
      <% end %>
    </td>
    <td><%= link_to 'Show', talk %></td>
    <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
    <td><%= link_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/new.html.erb
<h1>New talk</h1>

<%= render 'form' %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @talk.name %>
</p>

<p>
  <b>Description:</b>
  <%= @talk.description %>
</p>


<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>