config/routes.rb
Media::Application.routes.draw do

  root :to => 'talks#index'

  get "video/:id" => 'video#show'

  resources :media

  resources :confrences

  resources :presenters

  resources :talks

end

app/models/confrence.rb
class Confrence < ActiveRecord::Base
  attr_accessible :location, :name, :year
end

app/controllers/confrences_controller.rb
class ConfrencesController < ApplicationController
  # GET /confrences
  # GET /confrences.json
  def index
    @confrences = Confrence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @confrences }
    end
  end

  # GET /confrences/1
  # GET /confrences/1.json
  def show
    @confrence = Confrence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @confrence }
    end
  end

  # GET /confrences/new
  # GET /confrences/new.json
  def new
    @confrence = Confrence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @confrence }
    end
  end

  # GET /confrences/1/edit
  def edit
    @confrence = Confrence.find(params[:id])
  end

  # POST /confrences
  # POST /confrences.json
  def create
    @confrence = Confrence.new(params[:confrence])

    respond_to do |format|
      if @confrence.save
        format.html { redirect_to @confrence, notice: 'Confrence was successfully created.' }
        format.json { render json: @confrence, status: :created, location: @confrence }
      else
        format.html { render action: "new" }
        format.json { render json: @confrence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /confrences/1
  # PUT /confrences/1.json
  def update
    @confrence = Confrence.find(params[:id])

    respond_to do |format|
      if @confrence.update_attributes(params[:confrence])
        format.html { redirect_to @confrence, notice: 'Confrence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @confrence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /confrences/1
  # DELETE /confrences/1.json
  def destroy
    @confrence = Confrence.find(params[:id])
    @confrence.destroy

    respond_to do |format|
      format.html { redirect_to confrences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/confrences_helper.rb
module ConfrencesHelper
end

app/views/confrences/_form.html.erb
<%= form_for(@confrence) do |f| %>
  <% if @confrence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@confrence.errors.count, "error") %> prohibited this confrence from being saved:</h2>

      <ul>
      <% @confrence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/confrences/edit.html.erb
<h1>Editing confrence</h1>

<%= render 'form' %>

<%= link_to 'Show', @confrence %> |
<%= link_to 'Back', confrences_path %>

app/views/confrences/index.html.erb
<h1>Listing confrences</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @confrences.each do |confrence| %>
  <tr>
    <td><%= confrence.name %></td>
    <td><%= confrence.year %></td>
    <td><%= confrence.location %></td>
    <td><%= link_to 'Show', confrence %></td>
    <td><%= link_to 'Edit', edit_confrence_path(confrence) %></td>
    <td><%= link_to 'Destroy', confrence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Confrence', new_confrence_path %>

app/views/confrences/new.html.erb
<h1>New confrence</h1>

<%= render 'form' %>

<%= link_to 'Back', confrences_path %>

app/views/confrences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @confrence.name %>
</p>

<p>
  <b>Year:</b>
  <%= @confrence.year %>
</p>

<p>
  <b>Location:</b>
  <%= @confrence.location %>
</p>


<%= link_to 'Edit', edit_confrence_path(@confrence) %> |
<%= link_to 'Back', confrences_path %>