config/routes.rb
Media::Application.routes.draw do

  root :to => 'talks#index'

  get "video/:id" => 'video#show'

  resources :media

  resources :confrences

  resources :presenters

  resources :talks

end

app/models/presenter.rb
class Presenter < ActiveRecord::Base
  attr_accessible :aim, :email, :fbook, :handle, :linkedin, :name, :skype, :twitter, :url

  has_and_belongs_to_many :talks
end

app/controllers/presenters_controller.rb
class PresentersController < ApplicationController
  # GET /presenters
  # GET /presenters.json
  def index
    @presenters = Presenter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @presenters }
    end
  end

  # GET /presenters/1
  # GET /presenters/1.json
  def show
    @presenter = Presenter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @presenter }
    end
  end

  # GET /presenters/new
  # GET /presenters/new.json
  def new
    @presenter = Presenter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @presenter }
    end
  end

  # GET /presenters/1/edit
  def edit
    @presenter = Presenter.find(params[:id])
  end

  # POST /presenters
  # POST /presenters.json
  def create
    @presenter = Presenter.new(params[:presenter])

    respond_to do |format|
      if @presenter.save
        format.html { redirect_to @presenter, notice: 'Presenter was successfully created.' }
        format.json { render json: @presenter, status: :created, location: @presenter }
      else
        format.html { render action: "new" }
        format.json { render json: @presenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /presenters/1
  # PUT /presenters/1.json
  def update
    @presenter = Presenter.find(params[:id])

    respond_to do |format|
      if @presenter.update_attributes(params[:presenter])
        format.html { redirect_to @presenter, notice: 'Presenter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @presenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presenters/1
  # DELETE /presenters/1.json
  def destroy
    @presenter = Presenter.find(params[:id])
    @presenter.destroy

    respond_to do |format|
      format.html { redirect_to presenters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/presenters_helper.rb
module PresentersHelper
end

app/views/presenters/_form.html.erb
<%= form_for(@presenter) do |f| %>
  <% if @presenter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presenter.errors.count, "error") %> prohibited this presenter from being saved:</h2>

      <ul>
      <% @presenter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :handle %><br />
    <%= f.text_field :handle %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :fbook %><br />
    <%= f.text_field :fbook %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :linkedin %><br />
    <%= f.text_field :linkedin %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :skype %><br />
    <%= f.text_field :skype %>
  </div>
  <div class="field">
    <%= f.label :aim %><br />
    <%= f.text_field :aim %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presenters/edit.html.erb
<h1>Editing presenter</h1>

<%= render 'form' %>

<%= link_to 'Show', @presenter %> |
<%= link_to 'Back', presenters_path %>

app/views/presenters/index.html.erb
<h1>Listing presenters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Handle</th>
    <th>Email</th>
    <th>Fbook</th>
    <th>Twitter</th>
    <th>Linkedin</th>
    <th>Url</th>
    <th>Skype</th>
    <th>Aim</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @presenters.each do |presenter| %>
  <tr>
    <td><%= presenter.name %></td>
    <td><%= presenter.handle %></td>
    <td><%= presenter.email %></td>
    <td><%= presenter.fbook %></td>
    <td><%= presenter.twitter %></td>
    <td><%= presenter.linkedin %></td>
    <td><%= presenter.url %></td>
    <td><%= presenter.skype %></td>
    <td><%= presenter.aim %></td>
    <td><%= link_to 'Show', presenter %></td>
    <td><%= link_to 'Edit', edit_presenter_path(presenter) %></td>
    <td><%= link_to 'Destroy', presenter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Presenter', new_presenter_path %>

app/views/presenters/new.html.erb
<h1>New presenter</h1>

<%= render 'form' %>

<%= link_to 'Back', presenters_path %>

app/views/presenters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @presenter.name %>
</p>

<p>
  <b>Handle:</b>
  <%= @presenter.handle %>
</p>

<p>
  <b>Email:</b>
  <%= @presenter.email %>
</p>

<p>
  <b>Fbook:</b>
  <%= @presenter.fbook %>
</p>

<p>
  <b>Twitter:</b>
  <%= @presenter.twitter %>
</p>

<p>
  <b>Linkedin:</b>
  <%= @presenter.linkedin %>
</p>

<p>
  <b>Url:</b>
  <%= @presenter.url %>
</p>

<p>
  <b>Skype:</b>
  <%= @presenter.skype %>
</p>

<p>
  <b>Aim:</b>
  <%= @presenter.aim %>
</p>

<%= link_to 'Edit', edit_presenter_path(@presenter) %> |
<%= link_to 'Back', presenters_path %>